### ISSUE TITLE
Links in emails do not contain protocol

### ISSUE THREAD

**Issue by Bisaloo** [MTES-MCT/Dossier-Facile-Frontend#2]
Upon signing up to the service, the user receives an email that reads:

> Bonjour,
>
> Merci de faire confiance à Locatio. Pour activer votre compte, cliquez sur le lien suivant :
>
> locatio.beta.gouv.fr/changer-de-mot-de-passe/XXXXXX
>
> A bientôt,
> L'équipe Locatio 

The link do not have any protocol, which means it's not clickable. This might be on purpose and it's not too important.

But because `locatio.beta.gouv.fr` can only be reached over HTTPS (not plain HTTP), when the user copies/pastes this link to their URL bar, it won't work:

> Firefox can’t establish a connection to the server at locatio.beta.gouv.fr.

**Proposed fix**: provide a link to https://locatio.beta.gouv.fr instead or make the website reachable over HTTP (with a redirect to HTTPS and HSTS if you want to make sure it is only accessed over HTTPS).

**Comment by mattboll** [comment]
Hi,
Thank you for reaching us. The code here is deprecated (locatio is now named DossierFacile) The project is being fully rewritten and we won't fix the bug
