### ISSUE TITLE
Bug: Impossible de supprimer un compte: Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by Berjou** [MTES-MCT/Dossier-Facile-Frontend#347]
Testé avec firefox et chromium. Impossible de supprimer un compte avec l'erreur suivante: `CORS Missing Allow Origin`

**Comment by mattboll** [comment]
Bonjour,
Merci pour le retour, j'ai testé à l'instant et je n'ai pas eu de problème en production donc je soupçonne un cas particulier, peut-être avec un garant ou avec des colocataires par exemple.
Est-ce que pour faciliter la résolution du bug vous accepteriez de nous envoyer l'adresse e-mail utilisée ? En envoyant un message par mail à contact@dossierfacile.fr par exemple
Merci

**Comment by mattboll** [comment]
Bonjour,
Nous avons bien reçu l'email utilisé mais cela n'a pas permis de trouver le problème. Est-ce que le bug est toujours présent sur votre compte ? Pouvez-vous tester à nouveau et si cela ne fonctionne pas nous donner l'heure du test ?
Merci

**Comment by conema** [comment]
Hi,
Just a few days ago I contacted the support for this exact issue. After using the "supprimer mon compte" button, this error is shown:
![immagine](https://user-images.githubusercontent.com/12801153/132139568-f7d27588-1291-4fd1-b80b-8693af1fa96a.png)

After a while, I received an email that confirmed the closing of my account, but the account was still active: I could login and all my information were there. I tried to delete the account some other times, but the outcome was the same. At the end, I managed to delete it only by contacting the support.

**Comment by mattboll** [comment]
Hi,
I'm closing the issue as we won't use github to handle our issues. Rest assured that we will fix this bug as soon as we find the problem.
Regards

**Comment by mattboll** [comment]
NB : You can still send emails to contact@dossierfacile.fr if you have an issue
