### ISSUE TITLE
Document "Avis d'imposition" should not be asked for the guarantor

### ISSUE THREAD

**Issue by etiennebonnafoux** [MTES-MCT/Dossier-Facile-Frontend#415]
Hello,

According to the French law ( https://www.legifrance.gouv.fr/loda/id/JORFTEXT000031444493 ) in the document one can ask to the guarantor there is
```
E. - Un ou plusieurs documents attestant des ressources parmi les documents suivants :
1. Dernier avis d'imposition ou de non-imposition et, lorsque tout ou partie des revenus perçus n'a pas été imposé en France mais dans un autre Etat ou territoire, le dernier avis d'imposition à l'impôt ou aux impôts qui tiennent lieu d'impôt sur le revenu dans cet Etat ou territoire ou un document en tenant lieu établi par l'administration fiscale de cet Etat ou territoire.
2. Titre de propriété d'un bien immobilier ou dernier avis de taxe foncière.
3. Trois derniers bulletins de salaires.
4. Les deux derniers bilans ou, à défaut, une attestation de ressources pour l'exercice en cours délivré par un comptable pour les professions non salariées.
5. Justificatif de versement des indemnités, retraites, pensions, prestations sociales et familiales et allocations perçues lors des trois derniers mois ou justificatif de l'ouverture des droits, établis par l'organisme payeur.
6. Justificatif de revenus fonciers, de rentes viagères ou de revenus de valeurs et capitaux mobiliers.
```
but on dosser-facile there is :
<img width="695" alt="Capture d’écran 2021-09-06 à 21 33 50" src="https://user-images.githubusercontent.com/23340020/132256077-9c65e0a3-b7c9-4498-b766-b752e6363f15.png">
 It shouldn't be ask "justificatif de ressource" and "avis d'imposition" because just one of this document are ask in the French law.

**Comment by mattboll** [comment]
Hello,
Thank you for opening this issue, I understand that we shouldn't have both document mandatory. We have to improve the guarantor step to better reflect the law
I'll update this issue while we work on it

**Comment by mattboll** [comment]
No document is legally required, it is our choice to create standardized files that are easily understandable and accepted by agencies or owners.
Please send an email to contact@dossierfacile.fr for more information
