### ISSUE TITLE
Ajouter un lien pour télécharger tout le dossier en un clic

### ISSUE THREAD

**Issue by MEmmanuel** [MTES-MCT/Dossier-Facile-Frontend#47]
Bonjour,

J'ai utilisé DossierFacile pour faire mon dossier et ça marche très bien et c'est très pratique côté locataire.
J'ai discuté hier avec une agente immobilière qui m'a indiqué que c'était peu pratique de leur côté car elle devait cliquer sur la pièce, cliquer sur télécharger, fermer, cliquer sur une autre pièce etc..

Solution possible : Ajouter un lien "Télécharger tout le dossier", qui téléchargerait en ZIP le dossier complet avec tous les locataires.

Malheureusement, ne connaissant pas Vue, je ne peux pas proposer de PR pour l'instant.

Bonne journée !

**Comment by mattboll** [comment]
Bonjour,
Merci pour votre retour :)

La version en Vue.js n'est pas encore en production et l'interface sera légèrement différente.

Néanmoins concernant votre problème, lorsque vous allez sur votre compte (la page https://dossierfacile.fr/locataire/mon-compte ) Il y a un bouton "envoyer mon dossier", lorsque vous cliquez dessus il y a un lien du type https://dossierfacile.fr/dossier-locataire/RanD0m
C'est bien cette page que vous avez partagé à l'agente immobilière ? Dans ce cas, soit effectivement vous pouvez cliquer sur «voir pièce» pour voir une seule pièce, soit tout en bas de la page il y a un lien «Télécharger le dossier» qui contient le dossier complet (juste en dessous du gros bouton bleu)

Le lien en question n'est sans doute pas assez visible mais cela devrait être amélioré très prochainement

**Comment by MEmmanuel** [comment]
C'est bien cette page.
A yes en effet il y a déjà le bouton ! Je ne l'avais pas vu. Et c'est cool le doc est plus complet.
Peut être qu'il devrait être dans la typo gros bouton effectivement.
Ok bonne continuation alors :)
